language: crystal
before_install: crystal deps
install: crystal build --release src/*.cr
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "gemigrate"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "gemigrate"
    skip_cleanup: true
    name: edge
    prerelease: true
    overwrite: true
    on:
      tags: false
      branch: master
